//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsLogDataLoader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwsLogDataLoader.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.0
        ///15
        ///1  SQLCHAR		0	50		&quot; &quot;		1	RequestDateTime			SQL_Latin1_General_CP1_CI_AS
        ///2  SQLCHAR		0	50		&quot; &quot;		2	ProxyName				SQL_Latin1_General_CP1_CI_AS
        ///3  SQLCHAR		0	50		&quot; &quot;		3	SourceEndpoint			SQL_Latin1_General_CP1_CI_AS
        ///4  SQLCHAR		0	50		&quot; &quot;		4	DestinationEndpoint		SQL_Latin1_General_CP1_CI_AS
        ///5  SQLCHAR		0	12		&quot; &quot;		5	RequestProcessingTime	SQL_Latin1_General_CP1_CI_AS
        ///6  SQLCHAR		0	12		&quot; &quot;		6	BackendProcessingTime	SQL_Latin1_General_CP1_CI_AS
        ///7  SQLCHAR		0	12		&quot; &quot;		7	ResponseProcessingTime	SQL_Latin1_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormatFile {
            get {
                return ResourceManager.GetString("FormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [{0}]
        ///SELECT
        ///	CAST(RequestDateTime AS datetime2) [RequestDateTime],
        ///	CAST(ProxyName AS VARCHAR(50)) [ProxyName],
        ///	CAST(SourceEndpoint AS VARCHAR(50)) [SourceEndpoint],
        ///	CAST(DestinationEndpoint AS VARCHAR(50)) [DestinationEndpoint],
        ///	CAST(RequestProcessingTime AS DECIMAL(20, 12)) [RequestProcessingTime],
        ///	CAST(BackendProcessingTime AS DECIMAL(20, 12)) [BackendProcessingTime],
        ///	CAST(ResponseProcessingTime AS DECIMAL(20, 12)) [ResponseProcessingTime],
        ///	(CASE WHEN ElbStatusCode = &apos;-&apos; THEN  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadScript {
            get {
                return ResourceManager.GetString("LoadScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[{0}](
        ///	[RequestDateTime] [datetime2](7) NULL,
        ///	[ProxyName] [varchar](50) NULL,
        ///	[SourceEndpoint] [varchar](50) NULL,
        ///	[DestinationEndpoint] [varchar](50) NULL,
        ///	[RequestProcessingTime] [decimal](20, 12) NULL,
        ///	[BackendProcessingTime] [decimal](20, 12) NULL,
        ///	[ResponseProcessingTime] [decimal](20, 12) NULL,
        ///	[ElbStatusCode] [smallint] NULL,
        ///	[BackendStatusCode] [smallint] NULL,
        ///	[ReceivedBytes] [bigint] NULL,
        ///	[SentBytes] [bigint] NULL,
        ///	[Request] [varchar](max) NULL,
        ///	[UserA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableCreation_sql {
            get {
                return ResourceManager.GetString("TableCreation_sql", resourceCulture);
            }
        }
    }
}
